
name: AX Grammar

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  gen-grammar:
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-openvdb:2025-clang19.1
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./ci/build.sh -v --components=axgr --target=openvdb_ax_grammar --cargs=\"-DOPENVDB_AX_GRAMMAR_NO_LINES=ON\"
    - name: upload grammar
      uses: actions/upload-artifact@v4
      with:
        name: ax_grammar
        path: ./build/openvdb_ax/openvdb_ax/openvdb_ax/grammar
        retention-days: 5
